name: PR Build
on:
  pull_request:
    branches:
      - master

jobs:
  build-android:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.1
      - name: Checkout Submodules
        uses: textbook/git-checkout-submodule-action@2.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.0
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@babylonjs'
      - name: Yarn Install (Playground)
        run: yarn install
        working-directory: ./Apps/Playground
      - name: NPM Install (Package)
        run: npm install
        working-directory: ./Package
      - name: Gulp (Android)
        run: gulp buildAndroid
        working-directory: ./Package
