name: Publish Package
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.1
        with:
          submodules: 'recursive'
      - name: Setup Ninja
        run: brew install ninja
      - name: Yarn Install (Playground)
        run: yarn install
        working-directory: ./Apps/Playground
      - name: Pod Install (Playground)
        run: pod install
        working-directory: ./Apps/Playground/ios
      - name: CMake xcodeproj (Source Package)
        run: cmake -G Xcode -DCMAKE_TOOLCHAIN_FILE=../submodules/BabylonNative/Dependencies/ios-cmake/ios.toolchain.cmake -DPLATFORM=OS64COMBINED -DENABLE_ARC=0 -DDEPLOYMENT_TARGET=12 -DENABLE_GLSLANG_BINARIES=OFF -DSPIRV_CROSS_CLI=OFF .
        working-directory: ./Apps/Playground/node_modules/@babylonjs/react-native/ios
      - name: NPM Install (Binary Package)
        run: npm install
        working-directory: ./Package
      - name: Gulp
        run: npx gulp
        working-directory: ./Package
